<?php
/**
 * Created by PhpStorm.
 * User: smith
 * Date: 4/12/18
 * Time: 8:52 AM
 */

namespace App\Guards;


use Illuminate\Auth\SessionGuard;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Contracts\Auth\Guard;

class pinGuard extends SessionGuard {


	protected function hasValidCredentials( $user, $credentials ) {
		return parent::hasValidCredentials( $user, $credentials ); // TODO: Change the autogenerated stub
	}

	public function validate( array $credentials = [] ) {
		dd($credentials);
	}

}